homework_06/views/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import Length, DataRequired, Email


class PostForm(FlaskForm):
    title = StringField('title', validators=[Length(max=120), DataRequired()])
    body = StringField('body')


class SignupForm(FlaskForm):
    name = StringField('name', validators=[Length(max=100), DataRequired()])
    username = StringField('username', validators=[Length(max=100), DataRequired()])
    email = StringField('email', validators=[Length(max=120)])
    password = StringField('password', validators=[Length(min=4)])


class LoginForm(FlaskForm):
    email = StringField('email', validators=[Length(max=120)])
    password = StringField('password', validators=[Length(min=4)])

homework_06/main.py
import os

import click
from flask import Flask, render_template
from flask_migrate import Migrate
from flask_login import LoginManager

from blogproject import User, Post
from blogproject.database import db
from views.about import about_app
from views.auth import auth_app
from views.authors import authors_app
from views.posts import posts_app

PG_CONN_URI = os.environ.get("SQLALCHEMY_PG_CONN_URI") or "postgresql+pg8000://user:password@pg:5432/postgres"

app = Flask(__name__)
# simple key only for develop purpose
app.config['SECRET_KEY'] = 'secret-key-goes-here'

app.config['SQLALCHEMY_DATABASE_URI'] = PG_CONN_URI

db.init_app(app)

migrate = Migrate(app, db)

app.register_blueprint(about_app, url_prefix="/about")
app.register_blueprint(posts_app, url_prefix="/posts")
app.register_blueprint(authors_app, url_prefix="/authors")
app.register_blueprint(auth_app, url_prefix="/auth")

login_manager = LoginManager()
login_manager.login_view = 'auth_app.login'
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return db.session.execute(db.select(User).filter_by(id=int(user_id))).first()[0]


@app.cli.command("fill-db")
@click.argument("num")
def fill_in_table(num):
    num = int(num)
    for num in range(num):
        tmp_ath = User(name='user' + str(num),
                       username='suruser' + str(num),
                       email='user' + str(num) + '@mail.com')
        tmp_ath.set_password('test' + str(num))
        db.session.add(tmp_ath)
        for num_post in range(2):
            tmp_post = Post(title='Far' + str(num * num_post), body='far, far away', user=tmp_ath)
            db.session.add(tmp_post)
    db.session.commit()


@app.route('/', endpoint='index')
def index():
    users = db.session.execute(db.select(User).order_by(User.username)).scalars()
    return render_template('index.html', users=users)

homework_06/views/auth.py
from flask import (
    Blueprint,
    render_template, redirect, url_for, request, flash,
)
from flask_login import login_user, login_required, logout_user

from blogproject import User
from blogproject.database import db
from views.forms import SignupForm, LoginForm

auth_app = Blueprint("auth_app", __name__)


@auth_app.route('/login', endpoint='login', methods=['GET', 'POST'])
def login():
    form = LoginForm(meta={'csrf': False})
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember = True if request.form.get('remember') else False
        user = db.session.execute(db.select(User).filter_by(email=email)).first()[0]
        if not user or not user.check_password(password):
            flash('Please check your login details and try again.')
            return redirect(url_for('auth_app.login'))
        login_user(user, remember=remember)
        return redirect(url_for('index'))
    return render_template('auth/login.html', form=form)


@auth_app.route('/signup', endpoint='signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm(meta={'csrf': False})
    if form.validate_on_submit():
        email = form.email.data
        name = form.name.data
        username = form.username.data
        password = form.password.data
        user = db.session.execute(db.select(User).filter_by(email=email)).one_or_none()

        if user:
            return redirect(url_for('auth_app.signup'))

        new_user = User(email=email, name=name, username=username)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth_app.login'))

    return render_template('auth/signup.html', form=form)


@auth_app.route('/logout', endpoint='logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

homework_06/views/authors.py
from flask import (
    Blueprint,
    render_template, redirect, url_for,
)
from flask_login import login_required, current_user

from blogproject import User, Post
from blogproject.database import db
from views.forms import PostForm

authors_app = Blueprint("authors_app", __name__)


@authors_app.route('/<int:user_id>/', endpoint='author', methods=['GET', 'POST'])
def author(user_id):
    current_user
    auth = db.get_or_404(User, user_id)
    posts = db.session.execute(db.select(Post).where(Post.user_id == user_id)).scalars()
    form = PostForm(meta={'csrf': False})
    if form.validate_on_submit() and current_user.is_authenticated and current_user.id == auth.id:
        title = form.title.data
        body = form.body.data
        post = Post(title=title, body=body, user_id=auth.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('authors_app.author', user_id=user_id))
    return render_template('authors/author.html', author=auth, posts=posts, form=form, current_user=current_user)


@authors_app.route('<int:user_id>/<int:post_id>/', endpoint='post_delete', methods=['POST'])
@login_required
def post_delete(user_id, post_id):
    if current_user.is_authenticated and current_user.id == user_id:
        post = db.get_or_404(Post, post_id)
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('authors_app.author', user_id=user_id))

homework_06/views/posts.py
from flask import (
    Blueprint,
    render_template,
)

from blogproject import Post
from blogproject.database import db

posts_app = Blueprint("posts_app", __name__)


@posts_app.get('/', endpoint='posts')
def posts():
    poss = db.session.execute(db.select(Post).order_by(Post.title)).scalars()
    return render_template('posts/posts.html', posts=poss)


@posts_app.get('<int:auth_id>/<int:post_id>/', endpoint='post')
def post(auth_id, post_id):
    pos = db.get_or_404(Post, post_id)
    return render_template('posts/post.html', auth_id=auth_id, post=pos)

homework_06/templates/authors/author.html
{% extends 'base.html' %}
{% block content %}
    <h2>Blog by {{ author.name }} {{ author.surname }}</h2>
    <ul class="list-group list-group-flush">
    {% if posts %}
        {% for post in posts %}
          <li class="list-group-item">
            <div class="card w-50 mb-3">
              <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body }}</p>
                <a href={{ url_for('posts_app.post', auth_id=author.id, post_id=post.id) }} class="btn btn-primary">To post</a>
                {% if current_user.is_authenticated and current_user.id == author.id%}
                    <form method="POST"><button class="btn btn-primary" formaction={{ url_for('authors_app.post_delete', user_id=author.id, post_id=post.id) }}>Delete post</button></form>
                {% endif %}
              </div>
            </div>
          </li>
        {% endfor %}
    {% else %}
        No posts
    {% endif %}
    </ul>
    {% if current_user.is_authenticated and current_user.id == author.id%}
        <h1>Create post</h1>
        <form method="POST">
            {{ form.errors }}
            {{ form.title.label }} {{ form.title(class="form-control") }}
            {{ form.body.label }} {{ form.body(class="form-control") }}
            <input class="btn btn-primary" type="submit" value="Save">
        </form>
    {% endif %}
{% endblock %}

homework_06/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AstraBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href={{ url_for('index') }}>AstraBlog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={{ url_for('index') }}>Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={{ url_for('posts_app.posts') }}>Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('about_app.about') }}>About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('auth_app.login') }}>Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('auth_app.signup') }}>Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('auth_app.logout') }}>Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
        Content
    {% endblock %}
    <div class="container">
      <footer class="py-3 my-4 fixed-bottom">
        <p class="text-center text-body-secondary">&copy; 2023 Author, Inc</p>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

homework_06/templates/index.html
{% extends "base.html" %}
{% block content %}
    <ul class="list-group list-group-flush">
    {% if users %}
        {% for user in users %}
          <li class="list-group-item">
            <div class="card w-50 mb-3">
              <div class="card-body">
                <h5 class="card-title">Blog by {{ user.name }} {{ user.username }}</h5>
                <p class="card-text">With blog about big stars</p>
                <a href={{ url_for('authors_app.author', user_id = user.id) }} class="btn btn-primary">To posts</a>
              </div>
            </div>
          </li>
        {% endfor %}
    {% else %}
        No authors
    {% endif %}
    </ul>
{% endblock %}

homework_06/templates/posts/post.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ post.title }}</h2>
    <div class="container">
      <p>
          {{ post.body }}
      </p>
      <a href= {{ url_for('posts_app.posts') }} class="btn btn-primary">To posts</a>
      <a href= {{ url_for('authors_app.author', user_id=auth_id) }} class="btn btn-primary">To Author</a>
    </div>
{% endblock %}

homework_06/templates/posts/posts.html
{% extends 'base.html' %}
{% block content %}
    {% if posts %}
        {% for post in posts %}
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="card w-50 mb-3">
                  <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.body }}</p>
                    <a href={{ url_for('authors_app.author', user_id=post.user_id) }} class="btn btn-primary">To Author</a>
                    <a href={{ url_for('posts_app.post', auth_id=post.user_id, post_id=post.id) }} class="btn btn-primary">To Post</a>
                  </div>
                </div>
              </li>
        {% endfor %}
    {% else %}
        No post
    {% endif %}
    </ul>
{% endblock %}