homework_04_05/blogproject/blogproject/__init__.py
__all__ = (
    "User",
    "Post",
)

from blogproject.post import Post
from blogproject.user import User

homework_04_05/blogproject/main.py
import os
from sqlalchemy import create_engine
from flask import Flask, render_template

from blogproject.database import Base

from views.about import about_app
from views.authors import authors_app
from views.posts import posts_app

PG_CONN_URI = os.environ.get("SQLALCHEMY_PG_CONN_URI") or "postgresql+pg8000://user:password@localhost/postgres"

engine = create_engine(PG_CONN_URI, echo=True)

if __name__ == '__main__':
    Base.metadata.create_all(engine)

app = Flask(__name__)

app.register_blueprint(about_app, url_prefix="/about")
app.register_blueprint(posts_app, url_prefix="/posts")
app.register_blueprint(authors_app, url_prefix="/authors")


@app.route('/', endpoint='index')
def index():
    return render_template('index.html')

homework_04_05/blogproject/views/about.py
from flask import (
    Blueprint,
    render_template,
)

about_app = Blueprint("about_app", __name__)


@about_app.get('/', endpoint='about')
def about():
    return render_template('about/about.html')

homework_04_05/blogproject/views/authors.py
from flask import (
    Blueprint,
    render_template,
)

authors_app = Blueprint("authors_app", __name__)


@authors_app.get('/', endpoint='author')
def author():
    return render_template('authors/author.html')

homework_04_05/blogproject/views/posts.py
from flask import (
    Blueprint,
    render_template,
)

posts_app = Blueprint("posts_app", __name__)


@posts_app.get('/', endpoint='posts')
def posts():
    return render_template('posts/posts.html')


@posts_app.get('/post', endpoint='post')
def posts():
    return render_template('posts/post.html')

homework_04_05/blogproject/templates/about/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
      <h2>
        This page about AstraBlog
      </h2>
      <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
        and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
      </p>
    </div>
{% endblock %}

homework_04_05/blogproject/templates/authors/author.html
{% extends 'base.html' %}
{% block content %}
    <h2>Something about author</h2>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Post #1</h5>
            <p class="card-text">With post about big stars</p>
            <a href={{ url_for('posts_app.post') }} class="btn btn-primary">To post</a>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Post #2</h5>
            <p class="card-text">With blog about big stars</p>
            <a href={{ url_for('posts_app.post') }} class="btn btn-primary">To post</a>
          </div>
        </div>
      </li>
    </ul>
{% endblock %}

homework_04_05/blogproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AstraBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href={{ url_for('index') }}>AstraBlog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={{ url_for('authors_app.author') }}>Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={{ url_for('posts_app.posts') }}>Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('about_app.about') }}>About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
        Content
    {% endblock %}
    <div class="container">
      <footer class="py-3 my-4 fixed-bottom">
        <p class="text-center text-body-secondary">&copy; 2023 Author, Inc</p>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

homework_04_05/blogproject/templates/index.html
{% extends "base.html" %}
{% block content %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Blog by author</h5>
            <p class="card-text">With blog about big stars</p>
            <a href={{ url_for('authors_app.author') }} class="btn btn-primary">To posts</a>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Blog by author</h5>
            <p class="card-text">With blog about big stars</p>
            <a href={{ url_for('authors_app.author') }} class="btn btn-primary">To posts</a>
          </div>
        </div>
      </li>
    </ul>
{% endblock %}

homework_04_05/blogproject/templates/posts/post.html
{% extends 'base.html' %}
{% block content %}
    <h2>Post #1 by Author</h2>
    <div class="container">
      <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
        and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
      </p>
      <a href= {{ url_for('posts_app.posts') }} class="btn btn-primary">To posts</a>
      <a href= {{ url_for('authors_app.author') }} class="btn btn-primary">To Author</a>
    </div>
{% endblock %}

homework_04_05/blogproject/templates/posts/posts.html
{% extends 'base.html' %}
{% block content %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Posts about something</h5>
            <p class="card-text">This post about big stars</p>
            <a href={{ url_for('authors_app.author') }} class="btn btn-primary">To Author</a>
            <a href={{ url_for('posts_app.post') }} class="btn btn-primary">To Post</a>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="card w-50 mb-3">
          <div class="card-body">
            <h5 class="card-title">Posts about something</h5>
            <p class="card-text">This post about big stars</p>
            <a href={{ url_for('authors_app.author') }} class="btn btn-primary">To Author</a>
             <a href={{ url_for('posts_app.post') }} class="btn btn-primary">To Post</a>
          </div>
        </div>
      </li>
    </ul>
{% endblock %}